name: gastro_app
description: "App para descoberta de experiências gastronômicas"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.4.9
  
  # Supabase Integration
  supabase_flutter: ^2.3.4
  
  # Environment Variables
  flutter_dotenv: ^5.1.0
  
  # HTTP Requests
  http: ^1.1.2
  
  # Location Services
  geolocator: ^10.1.0
  
  # Google Maps
  google_maps_flutter: ^2.5.0
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # UI Components
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env 